### ISSUE TITLE
Unable to change video src React

### ISSUE THREAD

**Issue by Dester-Alken** [zhw2590582/ArtPlayer#242]
### Expected behaviour
I'm actually trying to create a settings menu which can change the video url (quality)
i'm using this method https://artplayer.org/document/en/Questions/How%20to%20add%20setting%20panel

### Actual behaviour
It is doing nothing rather throwing an error

### Steps to reproduce

Create a react app
use this FC
```
import Artplayer from "artplayer/examples/react/Artplayer";
import { useState } from "react";

function App() {
const [art, setArt] = useState(null);
    return (
      <div>
        <Artplayer
          option={{
            url: "https://artplayer.org/assets/sample/video.mp4",
            title: "Your Name",
            poster: "/assets/sample/poster.jpg",
            volume: 0.5,
            isLive: false,
            muted: false,
            autoplay: false,
            pip: true,
            autoSize: true,
            autoMini: true,
            screenshot: true,
            setting: true,
            loop: true,
            flip: true,
            playbackRate: true,
            aspectRatio: true,
            fullscreen: true,
            fullscreenWeb: true,
            subtitleOffset: true,
            miniProgressBar: true,
            mutex: true,
            backdrop: true,
            theme: "#23ade5",
            whitelist: ["*"],
            settings: [
              {
                html: "Select Subtitle",
                width: 250,
                tooltip: "Subtitle 01",
                selector: [
                  {
                    default: true,
                    html: '<span style="color:red">Subtitle 01</span>',
                    url: "/assets/sample/subtitle.srt?id=1",
                  },
                  {
                    html: '<span style="color:yellow">Subtitle 02</span>',
                    url: "/assets/sample/subtitle.srt?id=2",
                  },
                ],
                onSelect: function (item, $dom) {
                  console.info(item, $dom);
                  art.subtitle.url = item.url;

                  // Change the tooltip
                  return item.html;
                },
              },
              {
                html: "Select Quality",
                width: 150,
                tooltip: "1080P",
                selector: [
                  {
                    default: true,
                    html: "1080P",
                    url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
                  },
                  {
                    html: "720P",
                    url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
                  },
                  {
                    html: "360P",
                    url: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
                  },
                ],
                onSelect: function (item, $dom) {
                  console.info(item, $dom);
                  art.switchQuality(item.url, item.html);

                  // Change the tooltip
                  return item.html;
                },
              },
              {
                html: "Multi-layer nested",
                selector: [
                  {
                    html: "Nested 01",
                    selector: [
                      {
                        html: "Nested 02",
                      },
                      {
                        html: "Nested 02",
                      },
                    ],
                  },
                  {
                    html: "Nested 01",
                    selector: [
                      {
                        html: "Nested 02",
                      },
                      {
                        html: "Nested 02",
                      },
                    ],
                  },
                ],
              },
            ],
          }}
          style={{
            width: "600px",
            height: "400px",
            margin: "60px auto 0",
          }}
          getInstance={(art) => {
            art.on("ready", () => setArt(art));
          }}
        />
      </div>
    );
}

export default App;
```

### Environment

-   Browser: Chrome
-   Version: Version 99.0.4844.51 (Official Build) (x86_64)
-   Operating System: macOS
-   Version: 12.1 (21C52)

### Console errors (if any)
App.js:77 Uncaught TypeError: artplayer_examples_react_Artplayer__WEBPACK_IMPORTED_MODULE_0__.default.switchQuality is not a function
    at a.onSelect (App.js:77:1)
    at HTMLDivElement.<anonymous> (artplayer.js:8:1)

### Link to where the bug is happening
Locally

**Comment by zhw2590582** [comment]
Kind of weird, I'm going to look into this FC

but you can now use this: `this.switchQuality(item.url, item.html);`

**Comment by zhw2590582** [comment]
or you can use `useRef`

```js
import { useRef } from "react";

const player = useRef(null);

getInstance={(art) => {
     art.on("ready", () => {
         player.current = art;
     });
}}
```
