### ISSUE TITLE
self is not defined

### ISSUE THREAD

**Issue by hyjklmn** [zhw2590582/ArtPlayer#617]
使用nextjs打包构建时，```
self is not defined 
```
```

[18:45:42] Running build in Cleveland, USA (East) – cle1
[18:45:42] Cloning github.com/hyjklmn/next-live (Branch: master, Commit: 3e04183)
[18:45:43] Previous build cache not available
[18:45:43] Cloning completed: 409.639ms
[18:45:43] Running "vercel build"
[18:45:44] Vercel CLI 32.1.0
[18:45:44] Detected `pnpm-lock.yaml` version 6 generated by pnpm 8...
[18:45:44] Installing dependencies...
[18:45:45] Lockfile is up to date, resolution step is skipped
[18:45:45] Progress: resolved 1, reused 0, downloaded 0, added 0
[18:45:45] Packages: +440
[18:45:45] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[18:45:46] Progress: resolved 440, reused 0, downloaded 155, added 154
[18:45:47] Progress: resolved 440, reused 0, downloaded 371, added 363
[18:45:48] Progress: resolved 440, reused 0, downloaded 385, added 372
[18:45:49] Progress: resolved 440, reused 0, downloaded 440, added 439
[18:45:49] Progress: resolved 440, reused 0, downloaded 440, added 440, done
[18:45:50] 
[18:45:50] dependencies:
[18:45:50] + @radix-ui/react-avatar 1.0.3
[18:45:50] + @radix-ui/react-dropdown-menu 2.0.5
[18:45:50] + @radix-ui/react-icons 1.3.0
[18:45:50] + @radix-ui/react-scroll-area 1.0.4
[18:45:50] + @radix-ui/react-slot 1.0.2
[18:45:50] + @radix-ui/react-tabs 1.0.4
[18:45:50] + @types/node 20.4.10
[18:45:50] + @types/react 18.2.20
[18:45:50] + @types/react-dom 18.2.7
[18:45:50] + artplayer 5.0.9
[18:45:50] + artplayer-plugin-danmuku 5.0.1
[18:45:50] + autoprefixer 10.4.14
[18:45:50] + class-variance-authority 0.7.0
[18:45:50] + clsx 2.0.0
[18:45:50] + eslint 8.47.0
[18:45:50] + eslint-config-next 13.4.13
[18:45:50] + express 4.18.2
[18:45:50] + flv.js 1.6.2
[18:45:50] + framer-motion 10.16.4
[18:45:50] + hls.js 1.4.12
[18:45:50] + http-proxy-middleware 2.0.6
[18:45:50] + lucide-react 0.263.1
[18:45:50] + next 13.4.13
[18:45:50] + next-themes 0.2.1
[18:45:50] + postcss 8.4.27
[18:45:50] + react 18.2.0
[18:45:50] + react-dom 18.2.0
[18:45:50] + tailwind-merge 1.14.0
[18:45:50] + tailwindcss 3.3.3
[18:45:50] + tailwindcss-animate 1.0.7
[18:45:50] + theme-change 2.5.0
[18:45:50] + typescript 5.1.6
[18:45:50] 
[18:45:50] Done in 5.5s
[18:45:50] Detected Next.js version: 13.4.13
[18:45:50] Running "pnpm run build"
[18:45:50] 
[18:45:50] > next-app@0.0.1 build /vercel/path0
[18:45:50] > next build
[18:45:50] 
[18:45:51] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[18:45:51] This information is used to shape Next.js' roadmap and prioritize features.
[18:45:51] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[18:45:51] https://nextjs.org/telemetry
[18:45:51] 
[18:45:51] - info Creating an optimized production build...
[18:46:09] - info Compiled successfully
[18:46:09] - info Linting and checking validity of types...
[18:46:13] - info Collecting page data...
[18:46:24] - info Generating static pages (0/8)
[18:46:25] - info Generating static pages (2/8)
[18:46:25] - info Generating static pages (4/8)
[18:46:25]  ArtPlayer  5.0.9  https://artplayer.org
[18:46:25] ReferenceError: self is not defined
[18:46:25]     at 2455 (/vercel/path0/.next/server/chunks/91.js:40:4)
[18:46:25]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:42)
[18:46:25]     at 5539 (/vercel/path0/.next/server/app/(platform)/player/page.js:875:16)
[18:46:25]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:42)
[18:46:25]     at M (/vercel/path0/node_modules/.pnpm/next@13.4.13_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:24:46)
[18:46:25]     at ma (/vercel/path0/node_modules/.pnpm/next@13.4.13_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:28:324)
[18:46:25]     at Object.<anonymous> (/vercel/path0/node_modules/.pnpm/next@13.4.13_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:31:63)
[18:46:25]     at JSON.parse (<anonymous>)
[18:46:25]     at L (/vercel/path0/node_modules/.pnpm/next@13.4.13_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:23:53)
[18:46:25]     at c (/vercel/path0/node_modules/.pnpm/next@13.4.13_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:34:306)
[18:46:25] 
[18:46:25] Error occurred prerendering page "/player". Read more: https://nextjs.org/docs/messages/prerender-error
[18:46:25] ReferenceError: self is not defined
[18:46:25]     at 2455 (/vercel/path0/.next/server/chunks/91.js:40:4)
[18:46:25]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:42)
[18:46:25]     at 5539 (/vercel/path0/.next/server/app/(platform)/player/page.js:875:16)
[18:46:25]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:42)
[18:46:25]     at M (/vercel/path0/node_modules/.pnpm/next@13.4.13_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:24:46)
[18:46:25]     at ma (/vercel/path0/node_modules/.pnpm/next@13.4.13_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:28:324)
[18:46:25]     at Object.<anonymous> (/vercel/path0/node_modules/.pnpm/next@13.4.13_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:31:63)
[18:46:25]     at JSON.parse (<anonymous>)
[18:46:25]     at L (/vercel/path0/node_modules/.pnpm/next@13.4.13_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:23:53)
[18:46:25]     at c (/vercel/path0/node_modules/.pnpm/next@13.4.13_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:34:306)
[18:46:25] - info Generating static pages (6/8)
[18:46:25] - info Generating static pages (8/8)
[18:46:25] 
[18:46:25] > Export encountered errors on following paths:
[18:46:25] 	/(platform)/player/page: /player
[18:46:25]  ELIFECYCLE  Command failed with exit code 1.
[18:46:25] Error: Command "pnpm run build" exited with 1

```

**Comment by zhw2590582** [comment]
不太能确定是否播放器引起的，你可以找到是哪一行代码报错吗

**Comment by hyjklmn** [comment]
好，谢谢，我在看看
